apiVersion: v1
kind: Service
metadata:
  name: runnairaapp
  labels:
    app: runnairaapp
spec:
  selector:
    app: runnairaapp
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: flask
  type: NodePort

