name: Validate Infra YAML

on:
  push:
    paths:
      - 'runnaira-helm/**'
      - 'runnaira-kustomize/**'
  pull_request:
    paths:
      - 'runnaira-helm/**'
      - 'runnaira-kustomize/**'

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Helm templates YAML
        run: yamllint runnaira-helm/templates/

      - name: Validate Kustomize base YAML
        run: yamllint runnaira-kustomize/base/

      - name: Validate Kustomize overlays YAML
        run: yamllint runnaira-kustomize/overlays/
