name: Infra Config CI

on:
  push:
    paths:
      - 'runnaira-helm/**'
      - 'runnaira-kustomize/**'
  pull_request:
    paths:
      - 'runnaira-helm/**'
      - 'runnaira-kustomize/**'

jobs:
  validate-yaml:
    name: Validate YAML files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint

      - name: Lint Helm YAML files
        run: yamllint runnaira-helm/templates/

      - name: Lint Kustomize base
        run: yamllint runnaira-kustomize/base/

      - name: Lint Kustomize overlays
        run: yamllint runnaira-kustomize/overlays/

  helm-lint:
    name: Helm Chart Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run helm lint
        run: |
          sudo apt-get install -y curl
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm lint runnaira-helm

  kustomize-validate:
    name: Kustomize Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin

      - name: Build overlays/dev
        run: kustomize build runnaira-kustomize/overlays/dev

      - name: Build overlays/prod
        run: kustomize build runnaira-kustomize/overlays/prod
